### ISSUE TITLE
Build installable extension packages

### ISSUE THREAD

**Issue by pastak** [pastak/scboloo#3]
## TODO

- [x] Build Chrome Extension
- [x] Build Firefox Addon
- [ ] Build them on CI

## Future work

- [x] Build Extension for MS Edge
